//This file was generated by script mkregs.py

//address width
`define iob_im_swreg_ADDR_W 2

//address macros
//Write addresses
`define IM_BALL_LOC_ADDR 0
`define IM_BARL_LOC_ADDR 4
`define IM_BARR_LOC_ADDR 8
//Read Addresses

//register/mem data width
`define IM_BALL_LOC_W 32
`define IM_BARL_LOC_W 32
`define IM_BARR_LOC_W 32

//mem address width
